environment:
  env_id: "ALE/IceHockey-v5"
  n_envs: 1
  n_stack: 4

training:
  model_name: "dqn_test"
  total_timesteps: 200000
  eval_freq: 50000
  checkpoint_freq: 10000

dqn:
  policy: "CnnPolicy"
  learning_rate: 0.0001
  buffer_size: 30000 
  learning_starts: 1000 
  batch_size: 32 
  gamma: 0.99 
  train_freq: 4
  target_update_interval: 1000
  exploration_fraction: 0.1
  exploration_final_eps: 0.01
